### ISSUE TITLE
Tried deploying to heroku, failed.

### ISSUE THREAD

**Issue by joegaudet** [taichi/umlbot#1]
-----> Fetching set buildpack https://github.com/ddollar/heroku-buildpack-multi.git... done
-----> Multipack app detected
WARNING: This buildpack is no longer maintained.
Please choose a different buildpack or go to https://github.com/ddollar/heroku-buildpack-multi
and fork it to your own account.
This buildpack will cease to function at the stroke of midnight on January 1, 2017.
=====> Downloading Buildpack: https://github.com/weibeld/heroku-buildpack-graphviz-src.git
 !     Push rejected, failed to compile Multipack app

**Comment by taichi** [comment]
thanks for your report. i fixed all problmes and warnings.

please try to deploy to your heroku
